# Generated by Django 4.1.5 on 2023-02-21 01:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
